<?php
/**
 * PayU Supported Currencies – International / DCC payments
 *
 * List from PayU India documentation (130+ currencies for international payments):
 * https://docs.payu.in/docs/supported-currencies-for-international-payments
 *
 * @package PayU_Payment_Links
 */

defined( 'ABSPATH' ) || exit;

/**
 * Return PayU supported currencies (ISO code => currency name).
 * Used for Add Configuration dropdown and validation.
 *
 * @return array<string, string> ISO code => currency name
 */
function payu_get_supported_currencies() {
	static $currencies = null;
	if ( $currencies !== null ) {
		return $currencies;
	}
	$currencies = array(
		'AED' => __( 'UAE Dirham', 'payu-payment-links' ),
		'AFN' => __( 'Afghani', 'payu-payment-links' ),
		'ALL' => __( 'Lek', 'payu-payment-links' ),
		'AMD' => __( 'Armenian Dram', 'payu-payment-links' ),
		'ANG' => __( 'Netherlands Antillean Guilder', 'payu-payment-links' ),
		'AOA' => __( 'Kwanza', 'payu-payment-links' ),
		'ARS' => __( 'Argentine Peso', 'payu-payment-links' ),
		'AUD' => __( 'Australian Dollar', 'payu-payment-links' ),
		'AWG' => __( 'Aruban Florin', 'payu-payment-links' ),
		'AZN' => __( 'Azerbaijanian Manat', 'payu-payment-links' ),
		'BAM' => __( 'Convertible Mark', 'payu-payment-links' ),
		'BBD' => __( 'Barbados Dollar', 'payu-payment-links' ),
		'BGN' => __( 'Bulgarian Lev', 'payu-payment-links' ),
		'BHD' => __( 'Bahraini Dinar', 'payu-payment-links' ),
		'BIF' => __( 'Burundi Franc', 'payu-payment-links' ),
		'BMD' => __( 'Bermudian Dollar', 'payu-payment-links' ),
		'BND' => __( 'Brunei Dollar', 'payu-payment-links' ),
		'BOB' => __( 'Boliviano', 'payu-payment-links' ),
		'BRL' => __( 'Brazilian Real', 'payu-payment-links' ),
		'BSD' => __( 'Bahamian Dollar', 'payu-payment-links' ),
		'BWP' => __( 'Pula', 'payu-payment-links' ),
		'BYN' => __( 'Belarussian Ruble', 'payu-payment-links' ),
		'BZD' => __( 'Belize Dollar', 'payu-payment-links' ),
		'CAD' => __( 'Canadian Dollar', 'payu-payment-links' ),
		'CDF' => __( 'Congolese Franc', 'payu-payment-links' ),
		'CHF' => __( 'Swiss Franc', 'payu-payment-links' ),
		'CLP' => __( 'Chilean Peso', 'payu-payment-links' ),
		'CNY' => __( 'Yuan Renminbi', 'payu-payment-links' ),
		'COP' => __( 'Colombian Peso', 'payu-payment-links' ),
		'CRC' => __( 'Costa Rican Colon', 'payu-payment-links' ),
		'CVE' => __( 'Cabo Verde Escudo', 'payu-payment-links' ),
		'CZK' => __( 'Czech Koruna', 'payu-payment-links' ),
		'DJF' => __( 'Djibouti Franc', 'payu-payment-links' ),
		'DKK' => __( 'Danish Krone', 'payu-payment-links' ),
		'DOP' => __( 'Dominican Peso', 'payu-payment-links' ),
		'DZD' => __( 'Algerian Dinar', 'payu-payment-links' ),
		'EGP' => __( 'Egyptian Pound', 'payu-payment-links' ),
		'ETB' => __( 'Ethiopian Birr', 'payu-payment-links' ),
		'EUR' => __( 'Euro', 'payu-payment-links' ),
		'FJD' => __( 'Fiji Dollar', 'payu-payment-links' ),
		'FKP' => __( 'Falkland Islands Pound', 'payu-payment-links' ),
		'GBP' => __( 'Pound Sterling', 'payu-payment-links' ),
		'GEL' => __( 'Lari', 'payu-payment-links' ),
		'GHS' => __( 'Ghana Cedi', 'payu-payment-links' ),
		'GIP' => __( 'Gibraltar Pound', 'payu-payment-links' ),
		'GMD' => __( 'Dalasi', 'payu-payment-links' ),
		'GNF' => __( 'Guinea Franc', 'payu-payment-links' ),
		'GTQ' => __( 'Quetzal', 'payu-payment-links' ),
		'GYD' => __( 'Guyana Dollar', 'payu-payment-links' ),
		'HKD' => __( 'Hong Kong Dollar', 'payu-payment-links' ),
		'HNL' => __( 'Lempira', 'payu-payment-links' ),
		'HRK' => __( 'Kuna', 'payu-payment-links' ),
		'HTG' => __( 'Gourde', 'payu-payment-links' ),
		'HUF' => __( 'Forint', 'payu-payment-links' ),
		'IDR' => __( 'Rupiah', 'payu-payment-links' ),
		'ILS' => __( 'New Israeli Sheqel', 'payu-payment-links' ),
		'INR' => __( 'Indian Rupee', 'payu-payment-links' ),
		'IQD' => __( 'Iraqi Dinar', 'payu-payment-links' ),
		'ISK' => __( 'Iceland Krona', 'payu-payment-links' ),
		'JMD' => __( 'Jamaican Dollar', 'payu-payment-links' ),
		'JOD' => __( 'Jordanian Dinar', 'payu-payment-links' ),
		'JPY' => __( 'Yen', 'payu-payment-links' ),
		'KGS' => __( 'Som', 'payu-payment-links' ),
		'KHR' => __( 'Riel', 'payu-payment-links' ),
		'KMF' => __( 'Comoro Franc', 'payu-payment-links' ),
		'KRW' => __( 'Won', 'payu-payment-links' ),
		'KWD' => __( 'Kuwaiti Dinar', 'payu-payment-links' ),
		'KYD' => __( 'Cayman Islands Dollar', 'payu-payment-links' ),
		'KZT' => __( 'Tenge', 'payu-payment-links' ),
		'LAK' => __( 'Kip', 'payu-payment-links' ),
		'LBP' => __( 'Lebanese Pound', 'payu-payment-links' ),
		'LRD' => __( 'Liberian Dollar', 'payu-payment-links' ),
		'LSL' => __( 'Loti', 'payu-payment-links' ),
		'MAD' => __( 'Moroccan Dirham', 'payu-payment-links' ),
		'MDL' => __( 'Moldovan Leu', 'payu-payment-links' ),
		'MGA' => __( 'Malagasy Ariary', 'payu-payment-links' ),
		'MKD' => __( 'Denar', 'payu-payment-links' ),
		'MNT' => __( 'Tugrik', 'payu-payment-links' ),
		'MOP' => __( 'Pataca', 'payu-payment-links' ),
		'MRU' => __( 'Ouguiya', 'payu-payment-links' ),
		'MVR' => __( 'Rufiyaa', 'payu-payment-links' ),
		'MWK' => __( 'Kwacha', 'payu-payment-links' ),
		'MXN' => __( 'Mexican Peso', 'payu-payment-links' ),
		'MYR' => __( 'Malaysian Ringgit', 'payu-payment-links' ),
		'MZN' => __( 'Mozambique Metical', 'payu-payment-links' ),
		'NAD' => __( 'Namibia Dollar', 'payu-payment-links' ),
		'NGN' => __( 'Naira', 'payu-payment-links' ),
		'NIO' => __( 'Cordoba Oro', 'payu-payment-links' ),
		'NOK' => __( 'Norwegian Krone', 'payu-payment-links' ),
		'NZD' => __( 'New Zealand Dollar', 'payu-payment-links' ),
		'OMR' => __( 'Rial Omani', 'payu-payment-links' ),
		'PAB' => __( 'Balboa', 'payu-payment-links' ),
		'PEN' => __( 'Nuevo Sol', 'payu-payment-links' ),
		'PGK' => __( 'Kina', 'payu-payment-links' ),
		'PLN' => __( 'Zloty', 'payu-payment-links' ),
		'PYG' => __( 'Guarani', 'payu-payment-links' ),
		'QAR' => __( 'Qatari Rial', 'payu-payment-links' ),
		'RON' => __( 'Romanian Leu', 'payu-payment-links' ),
		'RSD' => __( 'Serbian Dinar', 'payu-payment-links' ),
		'RWF' => __( 'Rwanda Franc', 'payu-payment-links' ),
		'SAR' => __( 'Saudi Riyal', 'payu-payment-links' ),
		'SBD' => __( 'Solomon Islands Dollar', 'payu-payment-links' ),
		'SCR' => __( 'Seychelles Rupee', 'payu-payment-links' ),
		'SEK' => __( 'Swedish Krona', 'payu-payment-links' ),
		'SGD' => __( 'Singapore Dollar', 'payu-payment-links' ),
		'SHP' => __( 'Saint Helena Pound', 'payu-payment-links' ),
		'SOS' => __( 'Somali Shilling', 'payu-payment-links' ),
		'SRD' => __( 'Surinam Dollar', 'payu-payment-links' ),
		'SVC' => __( 'El Salvador Colon', 'payu-payment-links' ),
		'SZL' => __( 'Lilangeni', 'payu-payment-links' ),
		'THB' => __( 'Baht', 'payu-payment-links' ),
		'TJS' => __( 'Somoni', 'payu-payment-links' ),
		'TMT' => __( 'Turkmenistan New Manat', 'payu-payment-links' ),
		'TND' => __( 'Tunisian Dinar', 'payu-payment-links' ),
		'TOP' => __( "Pa'anga", 'payu-payment-links' ),
		'TRY' => __( 'Turkish Lira', 'payu-payment-links' ),
		'TTD' => __( 'Trinidad and Tobago Dollar', 'payu-payment-links' ),
		'TWD' => __( 'New Taiwan Dollar', 'payu-payment-links' ),
		'TZS' => __( 'Tanzanian Shilling', 'payu-payment-links' ),
		'UGX' => __( 'Uganda Shilling', 'payu-payment-links' ),
		'USD' => __( 'US Dollar', 'payu-payment-links' ),
		'UYU' => __( 'Peso Uruguayo', 'payu-payment-links' ),
		'UZS' => __( 'Uzbekistan Sum', 'payu-payment-links' ),
		'VES' => __( 'Venezuelan bolívar', 'payu-payment-links' ),
		'VND' => __( 'Dong', 'payu-payment-links' ),
		'VUV' => __( 'Vatu', 'payu-payment-links' ),
		'WST' => __( 'Tala', 'payu-payment-links' ),
		'XAF' => __( 'CFA Franc BEAC', 'payu-payment-links' ),
		'XCD' => __( 'East Caribbean Dollar', 'payu-payment-links' ),
		'XOF' => __( 'CFA Franc BCEAO', 'payu-payment-links' ),
		'XPF' => __( 'CFP Franc', 'payu-payment-links' ),
		'YER' => __( 'Yemeni Rial', 'payu-payment-links' ),
		'ZAR' => __( 'Rand', 'payu-payment-links' ),
		'ZMW' => __( 'Zambian Kwacha', 'payu-payment-links' ),
		'ZWL' => __( 'Zimbabwe Dollar', 'payu-payment-links' ),
	);
	return $currencies;
}
